# Taskfile (https://taskfile.dev)

version: "3"

# When tasks/commands are executed in parallel, the
# output should be prefixed with the name of the task,
# so it is easier to follow what is happening.
output: "prefixed"

# The interval to check for changes when watching tasks.
interval: "500ms"

tasks:

  lint:
    aliases: [ l ]
    desc: "Lint the codebase with the golangci-lint tool."
    cmds:
      - golangci-lint run

  test:
    aliases: [ t ]
    desc: "Execute all go tests."
    cmds:
      - go test ./...
